# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CC_TEST_REPORTER_ID: 3c17d30a957d0b5f06d932c3dd8ce9354df2b8d7769710d8827e6261445839d8

jobs:
    build:
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}

        strategy:
            fail-fast: true
            matrix:
                # test the current and previous LTS as well as latest stable release
                ember: ["ember-lts-3.20", "ember-lts-3.24", "ember-beta", "ember-default-with-jquery", "ember-classic"]
                experimental: [false]
                coverage: [false]
                include:
                    - ember: "ember-canary"
                      experimental: true
                      coverage: false
                    - ember: "ember-release"
                      experimental: false
                      coverage: true
        steps:
            - uses: actions/checkout@v2
            - name: Node setup
              uses: actions/setup-node@v2.1.2
              with:
                  # test addons with the same minimum supported node version as Ember CLI
                  # bumping to 12 since TailwindCSS uses flatmap, introduced in 11.x
                  node-version: "12.x"
            - name: Tests
              env:
                  EMBER_TRY_SCENARIO: ${{ matrix.ember }}
              run: |
                  npm ci
                  npm run lint
                  npm run test:ember

            # only run coverage under specific scenarios
            - name: Coverage
              if: ${{ matrix.coverage && github.ref == 'refs/heads/master' }}
              run: |
                  npm ci
                  COVERAGE=true node_modules/.bin/ember try:one ${{ matrix.ember }}
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter
                  ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
                  ./cc-test-reporter upload-coverage
